export const GET_ERRORS = 'GET_ERRORS';
export const AUTH_ERRORS = 'AUTH_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENT = 'GET_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
export const EVENT_LOADING = 'EVENT_LOADING';

export const CHANGE_SNACKBAR_MESSAGE = 'CHANGE_SNACKBAR_MESSAGE';

export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';

export const GET_NOTIFICATION = 'GET_NOTIFICATION';